### PR TITLE
Light gbm

### PR DESCRIPTION
**Pull request by aroraakshit**
light gbm results

### CODE REVIEW

**Comment by aroraakshit** [comment]
updated readme

**Comment by Hasil-Sharma** [comment]
@aroraakshit Why ? :rofl: ?

**Comment by aroraakshit** [comment]
@Hasil-Sharma  aren't we supposed to merge it to master after we are done with the model? I thought that's how it is. Never mind I ll close this :P

**Comment by Hasil-Sharma** [comment]
@aroraakshit you marked it for my review :rofl:

**Pull request closed without merging**
